const catchAsync = (asyncFn) => {
  return async (req, res, next) => {
    try {
      await asyncFn(req, res, next);
    } catch (err) {
      console.log("ðŸ”¥", err);
      next(err);
    }
  };
};

module.exports = catchAsync;
